### ISSUE TITLE
Apols amir to ask a question.

### ISSUE THREAD

**Issue by StuartIanNaylor** [amir73il/unionmount-testsuite#2]
`mount --verbose --types overlay -o lowerdir=$BIND_DIR,upperdir=/opt/zram$RAM_DEV/upper,workdir=/opt/zram$RAM_DEV/workdir overlay $ZRAM_DIR`

the 'workdir `overlay` $ZRAM_DIR' `overlay` in some examples I have seen as `none` but struggling to find exactly what that directive does apart stop the need of an fstab entry.
All the examples seem to gloss over any direct documentation and only by experimentation that on umount apart from a message the overlay mount did not exist all seems to work fine.
A DF shows it changes the filesystem txt as none or overlay will be listed as the file system for the mount.

Apols but wondering if someone of your stature would kindly maybe post a link or make a quick explanation to that directive?

**Comment by amir73il** [comment]
man mount(2) says:
 "mount() attaches the filesystem specified by source (which is often a
       pathname referring to a device, but can also be the pathname of a
       directory or file, or a dummy string)"

In case of overlayfs, as well as tmpfs, procfs, etc, source is a dummy string
You can put whatever you like in there but it seems to be a common convenstion
to put the fstype as the source string.

The dummy source string could be used as a key the the umount utility
if it is unique. For example, you could use '... workdir overlay$RAM_DEV $ZRAM_DIR'
and then you can use either command to unmount:
umount $ZRAM_DIR
umount overlay$RAM_DEV

**Comment by StuartIanNaylor** [comment]
Many thanks for your reply apols as did read but a usual doh from me.
Its just the umount gives me.
```
umount: /var/log (overlay) unmounted
umount: /opt/overlay: mountpoint not found
umount: /opt/log.bind/ unmounted
```
That was what puzzled me as apart from the dummy string there is no /opt/overlay. `umount: /opt/overlay: mountpoint not found`

Also it was tremendous of you to answer and many thanks, only if you have the time but the above is that normal?

I have been using zram as the upper with https://github.com/StuartIanNaylor/zram-config and the overlayfs is great for larger directories where instead of a copy for initial sync to volatile zram could be extensive.
Still trying to work out the best way to provide a merge without unmounting, dunno if you have any tips/hacks on doing that?
I am sort of thinking I will just write upper to persistant that if on boot persistant-upper exists it will get copied/moved lowersource before the new overlayfs mount.
Just to cope with crashes or powerouts with maybe periodic or user driven 'write outs' as didn't say merge as that can be automated on next boot, but if there are any merge tips/hacks out there I would be all ears :)
Still a work in progress and less said otherwise I will just ignore the `umount: /opt/overlay: mountpoint not found` puzzling message.

**Comment by amir73il** [comment]
It's not a puzzle just a bug in the script.
Commented on your project GitHub. Let's continue there if you have any questions
