### ISSUE TITLE
Test for overlayfs will need --xino flag to work

### ISSUE THREAD

**Issue by Cypresslin** [amir73il/unionmount-testsuite#5]
Hello,

we found that since commit 078708192bb ("Add support for user defined mount options") the command to run overlayfs test is not working anymore, it will fail with:

>  Running './run --ov'
 /mnt/a/foo100: File not on union layer
 Environment variables:
>
 >\***
 \*** ./run --ov --xino open-plain
 \***
 TEST open-plain.py:10: Open O_RDONLY

With some further research I found the mount command has changed.
Compare with the previous working mount command from mount_union.py:
* Working (019085f43d7e642 "Relax layers check for older kernels"):
  `mount -t overlay overlay /mnt -orw,`
  `redirect_dir=on,xino=on,lowerdir=/lower,upperdir=/upper/0/u,workdir=/upper/0/w`

* Not working (95be14ee4dd75c "Allow user provided options with or without -o")
  `mount -t overlay overlay /mnt -orw,`
  `redirect_dir=on -olowerdir=/lower,upperdir=/upper/0/u,workdir=/upper/0/w`

It's missing xino=on, so it looks like you need the --xino flag to enable it, and indeed the cases can pass with this flag.

Is this an expected behaviour? (Maybe the README needs to be updated with --xino flag added to test command examples)
Thanks!

**Comment by amir73il** [comment]
Not expected, but I suspect you are testing with kernel prior to commit
926e94d79baf ("ovl: enable xino automatically in more cases")
and with kernel config 
CONFIG_OVERLAY_FS_XINO_AUTO=y
Is that correct?

Please try this fix in run script after line 212:

> if redirect_dir is False:
>     cfg.add_mntopt("redirect_dir=on")
>     redirect_dir = True
> 
> if xino:
>       cfg.add_mntopt("xino=on")

This will "upgrade" the default xino=auto to xino=on which happens already with kernel >= v5.7
Let me know if it works and I will add this to the code

**Comment by Cypresslin** [comment]
Hello,
you're right, it's an Ubuntu Focal 5.4 kernel (5.4.0-58-generic) without commit 926e94d79baf and with `CONFIG_OVERLAY_FS_XINO_AUTO` set to `y`

And this fix works.
Thank you!

**Comment by amir73il** [comment]
pushed the fix.
Added you as Reporter/Tester.
Thanks!
